version: "3.8"

services:
  flask_app:
    build: .
    container_name: flask_sessao
    ports:
      - "5000:5000"
    environment:
      - SUPABASE_URL=https://<SEU_URL>.supabase.co
      - SUPABASE_KEY=<SUA_SUPABASE_KEY>
    restart: unless-stopped
